### ISSUE TITLE
Video thumbnails & profile pics are offset.

### ISSUE THREAD

**Issue by jdramirez165** [sakuramochi0/prichan-stylesheet#2]
Thats what it says on the title. The video thumbnails & the profile pics are just offset & it wasn't centered properly.

**Comment by sakuramochi0** [comment]
@jdramirez165 Thank you for the additional report.

![Screenshot from 2020-07-31 23-29-46](https://user-images.githubusercontent.com/6568716/89045015-c1937900-d385-11ea-98a2-577a94d4099b.png)

I think this problem is shown in the above image as a pink colored area. Right? If so, this problem will be fixed as well as the background problem as I said #1.🙂  Please wait for a while.

**Comment by sakuramochi0** [comment]
This issue should be fixed. Feel free to reopen if the problem remains.
